name = str(input("Type your name")).strip()
upper_name = name.upper()
print('Your name in uppercase is {}'.format(upper_name))
lower_name = name.lower()
print('Your name in lowercase is {}'.format(lower_name))
total_len_name = len(name) - name.count(' ')
print('Your name has {} characters'.format(total_len_name))
first_name = name.split()
print('Your first name is {}'.format(first_name[0].upper()))
